version: "3.7"
services:
  db:
    image: mysql:5.7
    container_name: mysql57
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: example 
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db-password
    networks:
      - pysql
  backend:
    build: backend
    ports:
    - "5000:5000"
    networks:
      - pysql
volumes:
  db-data:    
secrets:
  db-password:
    file: db/password.txt
networks:
  pysql:
  
