#FROM python:2.7-onbuild
FROM python:3.7-alpine as builder
WORKDIR /code
COPY  src/ /code/
RUN pip install -r requirements.txt
ENV FLASK_APP app.py
CMD flask run --host=0.0.0.0

#EXPOSE 5000
#CMD [ "python", "app.py" ]